#!/bin/sh
string=`curl -s --connect-timeout 1 -m 2 https://api.myip.com/ | jq '.ip + ", " + .cc' | sed 's/"//g'`

if [ "$string" == "" ]; then
  string='Disconnected'
  echo $string
  echo '#00ff00'
fi
if [[ $string == *", NL" ]]; then
  echo $string
  echo '#ff0000'
else
  echo $string
  echo '#00ff00'
fi
