#!/bin/sh
selected_password=`lpass ls --format="%ag/%an" | ~/.config/i3/scripts/rofi.sh -dmenu | sed 's/^\/\(.*\)/\1/g'`
if [[ $selected_password = '' ]]; then
  exit
else
  $selected_password =
  lpass user "$selected_password"
  notify-send -u low 'Username' -t 1000
  sleep 3
  lpass pass "$selected_password"
  notify-send -u low 'Password' -t 1000
  sleep 3
  xsel -bc
fi
